collections:
  staff:
    output: true
sass:
  sass_dir: _sass
  style: compressed
defaults:
  - scope:
      path: ""
      type: "staff"
    values:
      layout: "staff"
  - scope:
      path: ""
    values:
      layout: "default"
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
